Authorization credentials
dsimp/industrial-auth-1 pull request #1
Opened 2024-10-31 20:27 UTC by dsimp

2024-10-31 20:44 UTC, Testell requested changes
Everything looks good so far, you just need to apply the same logic to likes and follow_requests!

2024-10-31 20:44 UTC, Testell commented on app/controllers/comments_controller.rb
> +    end
Nice job securing the comments here!

2024-10-31 20:44 UTC, Testell commented on app/controllers/photos_controller.rb
> +    end
Nice job using  conventional naming

2024-11-01 16:38 UTC, bibimbop123 approved these changes
picasso of code

2024-11-01 22:10 UTC, viviancreates approved these changes

2024-11-01 22:10 UTC, viviancreates commented on app/controllers/comments_controller.rb
Good use of the before action

2024-11-01 22:10 UTC, viviancreates commented on app/controllers/photos_controller.rb
Nice, the before action restricts only necessary action

2024-11-01 22:10 UTC, viviancreates commented on app/models/comment.rb
Good association

2024-11-05 05:43 UTC, marywebby requested changes
Good work! Please fix the follow request controllers, and make sure to edit your routes too!! Please fix and re-request me!

2024-11-05 05:43 UTC, marywebby commented on app/controllers/comments_controller.rb
> +      if current_user != @photo.owner && @photo.owner.private? && !current_user.leaders.include?(@photo.owner)        redirect_back fallback_location: root_url, alert: "Not authorized"
make sure the `redirect_back` is on the next line

2024-11-05 05:43 UTC, marywebby commented on app/controllers/follow_requests_controller.rb
>    def edit
make sure you are setting the `:is_authorized_user` here at the top of the controller!

2024-11-05 05:43 UTC, marywebby commented on app/controllers/likes_controller.rb
> +  def is_an_authorized_user
good!

2024-11-05 05:43 UTC, marywebby commented on app/controllers/photos_controller.rb
> +    if current_user == @photo.owner
good! make sure to clean up the indentation and spacing

2024-11-05 05:43 UTC, marywebby commented on app/policies/photo_policy.rb
> +class PhotoPolicy
this is for pundit! dont need it here

2024-11-06 15:13 UTC, merged